apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

commonLabels:
  app: saml-exporter

images:
- name: doodlescheduling/saml-exporter:latest
  newTag: 0.0.1
