{{- if .Values.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "saml-exporter.fullname" . }}
  labels:
    {{- include "saml-exporter.labels" . | nindent 4 }}
    {{- with .Values.podMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if or .Values.annotations .Values.podMonitor.annotations }}
  annotations:
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.podMonitor.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}  
  {{- if .Values.podMonitor.namespace }}
  namespace: {{ .Values.podMonitor.namespace }}
  {{- end }}
spec:
  podMetricsEndpoints:
  - path: {{ .Values.metricsPath }}
    {{- if .Values.kubeRBACProxy.enabled }}
    port: https-metrics
    scheme: https
    bearerTokenSecret:
      key: token
      name: {{ template "saml-exporter.serviceAccountName" . }}
    tlsConfig:
      insecureSkipVerify: true
    {{- else }}
    port: http-metrics
    {{- end }}
    interval: {{ .Values.podMonitor.interval }}
    scrapeTimeout: {{ .Values.podMonitor.scrapeTimeout }}
    {{- if .Values.podMonitor.metricRelabelings }}
    metricRelabelings: {{ toYaml .Values.podMonitor.metricRelabelings | nindent 4 }}
    {{- end }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "saml-exporter.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- if .Values.podMonitor.targetLabels }}
  targetLabels:
{{- range .Values.podMonitor.targetLabels }}
    - {{ . }}
{{- end }}
{{- end }}
  sampleLimit: {{ .Values.podMonitor.sampleLimit }}
{{- end }}
