{{- if .Values.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
metadata:
  name: {{ template "saml-exporter.fullname" . }}
  labels: {{- merge ( include "saml-exporter.labels" . | fromYaml) .Values.prometheusRule.labels | toYaml | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.prometheusRule.namespace }}
  namespace: {{ .Values.prometheusRule.namespace }}
  {{- end }}
spec:
{{- with .Values.prometheusRule.rules }}
  groups:
    - name: {{ template "saml-exporter.name" $ }}
      rules: {{ tpl (toYaml .) $ | nindent 8 }}
{{- end }}
{{- end }}
