{{- if .Values.prometheusRule.enabled }}
{{- $rulePrefix:= .Values.prometheusRule.rulePrefix }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ template "saml-exporter.fullname" . }}
  labels:
    {{- include "saml-exporter.labels" . | nindent 4 }}
    {{- with .Values.prometheusRule.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if or .Values.annotations .Values.prometheusRule.annotations }}
  annotations:
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.prometheusRule.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}  
  {{- if .Values.prometheusRule.namespace }}
  namespace: {{ .Values.prometheusRule.namespace }}
  {{- end }}
spec:
  groups:
  {{- if .Values.prometheusRule.disableBuiltinAlertGroup }}
    {{- if not (len .Values.prometheusRule.extraAlertGroups) }}
      {{ fail "Extra alert groups (extraAlertGroups) are required when disableBuiltinAlertGroup is set!" }}
    {{- end }}
  {{- else }}
  - name: saml-exporter.rules
    rules:
    {{- if .Values.prometheusRule.alertOnReadErrors }}
    - alert: '{{ printf "%s%s" $rulePrefix "X509CertificateReadErrors" | trim }}'
      expr: delta(saml_x509_read_errors_total[15m]) > 0
      for: 5m
      labels:
        severity: {{ .Values.prometheusRule.readErrorsSeverity }}
        {{- if .Values.prometheusRule.alertExtraLabels }}
        {{- toYaml .Values.prometheusRule.alertExtraLabels | nindent 8 }}
        {{- end }}
      annotations:
        summary: Increasing certificate parse errors for saml-exporter
        description: Over the last 15 minutes, this saml-exporter instance has experienced errors parsing certificates from saml metadata.
        {{- if .Values.prometheusRule.alertExtraAnnotations }}
        {{- toYaml .Values.prometheusRule.alertExtraAnnotations | nindent 8 }}
        {{- end }}
    {{- end }}
    {{- if .Values.prometheusRule.alertOnMetadataErrors }}
    - alert: '{{ printf "%s%s" $rulePrefix "MetadataError" | trim }}'
      expr: delta(saml_metadata_errors_total[15m]) > 0
      for: 5m
      labels:
        severity: {{ .Values.prometheusRule.metadataErrorsSeverity }}
        {{- if .Values.prometheusRule.alertExtraLabels }}
        {{- toYaml .Values.prometheusRule.alertExtraLabels | nindent 8 }}
        {{- end }}
      annotations:
        summary: Increasing saml metadata errors for saml-exporter
        description: Over the last 15 minutes, this saml-exporter instance has experienced errors parsing saml metadata
        {{- if .Values.prometheusRule.alertExtraAnnotations }}
        {{- toYaml .Values.prometheusRule.alertExtraAnnotations | nindent 8 }}
        {{- end }}
    {{- end }}
    - alert: '{{ printf "%s%s" $rulePrefix "X509CertificateRenewal" | trim }}'
      expr: count(saml_x509_cert_not_valid_after) by (entityid, use) - count(((saml_x509_cert_not_valid_after - time()) / 86400) < {{ .Values.prometheusRule.warningDaysLeft }}) by (entityid, use) == 0
      for: 15m
      labels:
        severity: {{ .Values.prometheusRule.certificateRenewalsSeverity }}
        {{- if .Values.prometheusRule.alertExtraLabels }}
        {{- toYaml .Values.prometheusRule.alertExtraLabels | nindent 8 }}
        {{- end }}
      annotations:
        summary: Certificate should be renewed
        description: Certificate for "{{ "{{" }} $labels.subject_CN {{ "}}" }}" should be renewed
        {{- if .Values.prometheusRule.alertExtraAnnotations }}
        {{- toYaml .Values.prometheusRule.alertExtraAnnotations | nindent 8 }}
        {{- end }}
    - alert: '{{ printf "%s%s" $rulePrefix "X509CertificateExpiration" | trim }}'
      expr: count(saml_x509_cert_not_valid_after) by (entityid, use) - count(((saml_x509_cert_not_valid_after - time()) / 86400) < {{ .Values.prometheusRule.criticalDaysLeft }}) by (entityid, use) == 0
      for: 15m
      labels:
        severity: {{ .Values.prometheusRule.certificateExpirationsSeverity }}
        {{- if .Values.prometheusRule.alertExtraLabels }}
        {{- toYaml .Values.prometheusRule.alertExtraLabels | nindent 8 }}
        {{- end }}
      annotations:
        summary: All certificates are soon expiring. There will be no certificate left for rotation which is valid.
        description: Certificate for "{{ "{{" }} $labels.subject_CN {{ "}}" }}" should be renewed
        {{- if .Values.prometheusRule.alertExtraAnnotations }}
        {{- toYaml .Values.prometheusRule.alertExtraAnnotations | nindent 8 }}
        {{- end }}
    - alert: '{{ printf "%s%s" $rulePrefix "UnavailableMetadataEndpoint" | trim }}'
      expr: sum(rate(http_client_requests_total{job="{{ .Values.podMonitor.namespace | default .Values.serviceMonitor.namespace | default .Release.Namespace}}/{{ include "saml-exporter.fullname" . }}", code!~"^2.*"}[5m])) by (host) > 0
      for: 3m
      labels:
        severity: {{ .Values.prometheusRule.unavailableMetadataEndpointSeverity }}
        {{- if .Values.prometheusRule.alertExtraLabels }}
        {{- toYaml .Values.prometheusRule.alertExtraLabels | nindent 8 }}
        {{- end }}
      annotations:
        summary: A SAML metadata endpoint is unreachable
        description: A SAML metadata endpoint "{{ "{{" }} $labels.host {{ "}}" }}" is not responding with a 2xx code for over 5m.
        {{- if .Values.prometheusRule.alertExtraAnnotations }}
        {{- toYaml .Values.prometheusRule.alertExtraAnnotations | nindent 8 }}
        {{- end }}
  {{- end }}
{{- range .Values.prometheusRule.extraAlertGroups }}
  - {{ tpl (toYaml .) $ | indent 4 | trim }}
{{- end }}
{{- end }}
