{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "saml-exporter.serviceAccountName" . }}
  labels:
    {{- include "saml-exporter.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ template "saml-exporter.serviceAccountName" . }}
type: kubernetes.io/service-account-token
{{- end -}}
