{{ if or .Values.service.enabled .Values.serviceMonitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "saml-exporter.fullname" . }}
  labels:
    {{- include "saml-exporter.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if or .Values.annotations .Values.service.annotations }}
  annotations:
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}  
spec:
  ports:
    {{- if .Values.kubeRBACProxy.enabled }}
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: https-metrics
      protocol: TCP
      targetPort: https-metrics
    {{- else }}
    - port: {{ .Values.service.port }}
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "saml-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ .Values.service.type }}
{{- end }}
