{
 "title": "SAML Metadata",
 "description": "Dashboard for SAML metadata",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   { "name": "critical_threshold", "label": "Critical Threshold (days)", "query": "1,7,14,15,28,30,60,90,180,365" },
   { "name": "warning_threshold", "label": "Warning Threshold (days)", "query": "1,7,14,15,28,30,60,90,180,365" },
   {
    "name": "list_threshold",
    "label": "List expiring in less than (days)",
    "query": "1,7,15,30,60,90,180,365,730,1095,1460,1825,3650,7300"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Certificates",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(saml_x509_cert_not_after)"
    }
   ]
  },
  {
   "title": "Expired Certificates",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(((saml_x509_cert_not_after - time()) / 86400) < bool 0)"
    }
   ]
  },
  {
   "title": "Expiring within $critical_threshold days",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(0 < ((saml_x509_cert_not_after - time()) / 86400) < bool $critical_threshold)"
    }
   ]
  },
  {
   "title": "Unavailable SAML Metadata",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(rate(http_client_request{code!~\"^2.*\", job=~\".*/saml-exporter\"}[$__rate_interval])) by (host))"
    }
   ]
  },
  {
   "title": "SAML Endpoints with critical amount of valid certificates left",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(count(saml_x509_cert_not_after) by (entityid) - count(((saml_x509_cert_not_after - time()) / 86400) < $critical_threshold) by (entityid) == 0)) or vector(0)",
     "legendFormat": "{{entityid}}"
    }
   ]
  },
  {
   "title": "Exporters",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(saml_exporter_build_info)"
    }
   ]
  },
  {
   "title": "Expiring within $warning_threshold days",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(0 < ((saml_x509_cert_not_after - time()) / 86400) < bool $warning_threshold)"
    }
   ]
  },
  {
   "title": "Exporter Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(saml_x509_read_errors) or vector(0)) + (sum(saml_metadata_errors) or vector(0))"
    }
   ]
  },
  {
   "title": "Certificates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Certificates (time left < $list_threshold days)",
   "type": "table",
   "description": "Because of a missing feature in Grafana, critical and warning thresholds from dashboard variables will not affect coloration of the Time Left column in this table.\n\nThresholds are to be set manually in the Overrides settings for this widget.\n\nPlease vote or contribute to issue : https://github.com/grafana/grafana/issues/922",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sort(((saml_x509_cert_not_after{} - time()) / 86400) < $list_threshold)"
    }
   ]
  },
  {
   "title": "Top Issuers",
   "type": "table",
   "gridPos": { "h": 13, "w": 8, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "topk(10, sort_desc(count by (issuer_CN) (saml_x509_cert_not_after)))"
    }
   ]
  },
  {
   "title": "Shortest Validity Period",
   "type": "table",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "bottomk(10, (saml_x509_cert_not_after{} - saml_x509_cert_not_before) / 86400)"
    }
   ]
  },
  {
   "title": "Longest Validity Period",
   "type": "table",
   "gridPos": { "h": 11, "w": 10, "x": 10, "y": 27 },
   "targets": [
    {
     "expr": "topk(10, (saml_x509_cert_not_after - saml_x509_cert_not_before) / 86400)"
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Metadata endpoint HTTP response codes over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum(rate(http_client_request{job=~\".*/saml-exporter\"}[$__rate_interval])) by (code, host)",
     "legendFormat": "{{host}}: {{code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Exporters with Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum((saml_x509_read_errors or vector(0)) > bool 0)",
     "legendFormat": "Certificate parsing errors"
    },
    {
     "expr": "sum((saml_metadata_errors or vector(0)) > bool 0)",
     "legendFormat": "Metadata parsing errors"
    }
   ]
  },
  {
   "title": "Cumulative Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(saml_x509_read_errors) or vector(0)",
     "legendFormat": "Certificate parsing errors"
    },
    {
     "expr": "sum(saml_metadata_errors) or vector(0)",
     "legendFormat": "Metadata parsing errors"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(saml_x509_read_errors[$__rate_interval])) or vector(0)",
     "legendFormat": "Certificate parsing errors"
    },
    {
     "expr": "sum(rate(saml_metadata_errors[$__rate_interval])) or vector(0)",
     "legendFormat": "Metadata parsing errors"
    }
   ]
  },
  {
   "title": "Top Exporters by Cumulative Errors",
   "type": "table",
   "gridPos": { "h": 13, "w": 9, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "topk(10, saml_x509_read_errors)"
    },
    { "expr": "topk(10, saml_metadata_errors)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Top Exporters by Error Rate",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "topk(10, rate(saml_x509_read_errors[6h]))"
    },
    {
     "expr": "topk(10, rate(saml_metadata_errors[6h]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}